permalink: /:categories/:title/
email: shovelcode@gmail.com
author: kim jin woo

github : https://github.com/jinwho
itch : https://jinwho.itch.io/
codepen : https://codepen.io/jinwho/
glitch : https://glitch.com/@jinwho

profile_image: /assets/img/profile.png
